# Generated by Django 4.1 on 2022-08-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('nacimiento', models.DateField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Poder',
        ),
        migrations.DeleteModel(
            name='SuperHeroe',
        ),
    ]
